######
# This is not meant as an actual exercise to run, but to give an idea of how a complex practical
# example might look like.
######
# Role may take the following optional variables (defaults are defined in defaults/main.yml):
# mantid_versions: list, a list of versions defining the versions to install
# nightly_flag: boolean, will install nightly version if True
# mantid51_flag: boolean, if MantidPlot from v5.1 is required in addition to a newer Mantid version

- include_role: name=software/utilities/mambaforge

# Install libXScrnSaver as Workbench from Conda won't start
- name: Installing libXScrnSaver
  yum:
    name: libXScrnSaver

- name: Construct install information facts for release versions
  vars:
    software_analysis_mantid_install_info:
      version: "{{ software_analysis_mantid_version | string }}"
      channel: "mantid"
      install_prefix: "/opt/mantidworkbench{{ software_analysis_mantid_version | string }}"
  set_fact:
    software_analysis_mantid_install_infos: "{{ software_analysis_mantid_install_infos | default([]) | union([software_analysis_mantid_install_info]) }}"
  loop: "{{ mantid_versions }}"
  loop_control:
    loop_var: software_analysis_mantid_version

- name: Add nightly install information
  vars:
    software_analysis_mantid_install_info:
      version: "Nightly"
      channel: "mantid/label/nightly"
      install_prefix: "{{ install_prefix_nightly }}"
  set_fact:
    software_analysis_mantid_install_infos: "{{ software_analysis_mantid_install_infos | union([software_analysis_mantid_install_info]) }}"
  when: nightly_flag | bool

- name: Create conda environments for specified MantidWorkbench versions
  vars:
    version_specifier: >-
      {{
        (software_analysis_mantid_install_info['version'] != 'Nightly')
        | ternary('=' + software_analysis_mantid_install_info['version']
        | string, '')
      }}
  shell: |
    mamba create --prefix {{ software_analysis_mantid_install_info['install_prefix'] }}
    mamba install --yes --channel {{ software_analysis_mantid_install_info['channel'] }} \
      --prefix {{ software_analysis_mantid_install_info['install_prefix'] }} mantidworkbench{{ version_specifier }}
  changed_when: true
  loop: "{{ software_analysis_mantid_install_infos }}"
  loop_control:
    loop_var: software_analysis_mantid_install_info

- name: Conda install any additional packages required
  command: >
    mamba install
    --yes
    --prefix {{ software_analysis_mantid_install_info['install_prefix'] }}
    {{ conda_extras | join(' ') }}
  loop: "{{ software_analysis_mantid_install_infos }}"
  loop_control:
    loop_var: software_analysis_mantid_install_info
  when: conda_extras is defined

- name: Pip install any additional packages requested
  command: >
    mamba run
    --prefix {{ software_analysis_mantid_install_info['install_prefix'] }}
    pip install --no-input {{ pip_extras | join(' ') }}
  loop: "{{ software_analysis_mantid_install_infos }}"
  loop_control:
    loop_var: software_analysis_mantid_install_info
  when: pip_extras is defined

- name: Create desktop shortcuts
  template:
    src: mantid_workbench.desktop.j2
    dest: /etc/xdg/applications/mantid_workbench{{ software_analysis_mantid_install_info['version'] }}.desktop
    owner: root
    mode: 0444
  loop: "{{ software_analysis_mantid_install_infos }}"
  loop_control:
    loop_var: software_analysis_mantid_install_info

- name: Copy across Mantid Workbench icon
  copy:
    src: mantid_workbench.png
    dest: /usr/share/pixmaps/mantid_workbench.png
    mode: 0644

- name: Copy across MantidWorkbench Nightly icon
  copy:
    src: mantid_workbenchnightly.png
    dest: /usr/share/pixmaps/mantid_workbenchnightly.png
    mode: 0644
  when: nightly_flag | bool

- name: Add cron job to update MantidWorkbench Nightly
  cron:
    name: "Update MantidWorkbench Nightly"
    minute: "0"
    hour: "2"
    job: "mamba activate {{ install_prefix_nightly }} && mamba update --all -y"
  when: nightly_flag | bool

- name: Install ipykernel for MantidWorkbench versions to use it in Jupyter
  command:
    cmd: >
      {{ software_analysis_mantid_install_info['install_prefix'] }}/bin/ipython kernel install
      --name=mantid-{{ software_analysis_mantid_install_info['version'] }}
  loop: "{{ software_analysis_mantid_install_infos }}"
  loop_control:
    loop_var: software_analysis_mantid_install_info
  changed_when: true

- name: Create optional /etc/mantid.local.properties file
  file:
    path: "/etc/mantid.local.properties"
    state: touch
    mode: 0666

# This registers the number of GPUs present (literally the number of NVIDIA pci cards), as a STRING
- name: Register number of GPUs
  shell:
    cmd: lspci | grep NVIDIA | wc -l
    warn: no
  changed_when: false
  register: gpus_present

- name: Enable OpenGL in Mantid if Nvidia GPU present
  lineinfile:
    path: /etc/mantid.local.properties
    regexp: 'MantidOptions\.InstrumentView\.UseOpenGL =.*\n'
    line: MantidOptions.InstrumentView.UseOpenGL = {{ 'On' if gpus_present.stdout != "0" else 'Off' }}

- name: Install an additional Mantid version (v5.1) from rpm if required
  import_tasks: mantid51.yml
  when: mantid51_flag | bool


